repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        files: \.(yaml|yml)$
      - id: check-json
        exclude: ^(.devcontainer/devcontainer\.json|\.vscode/.*)$
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  # Python: Ruff linter and formatter (replaces Black, Flake8, isort)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  # Python: Type checking (temporarily disabled during Ruff migration)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        # Skip mypy temporarily during Ruff migration
        # TODO: Fix type stubs and interface violations
        stages: [manual]
        additional_dependencies: [types-requests]

  # JavaScript/CSS formatting and linting
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.35.0
    hooks:
      - id: eslint
        files: site/.*\.(js|ts)$
        additional_dependencies:
          - eslint@8.44.0
          - eslint-config-standard@17.1.0

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: site/.*\.(js|ts|css|html|json|md)$
        additional_dependencies:
          - prettier@3.0.0
