name: pylint
on: [push]
jobs:
  run-pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Runs pylint
        run: pylint **/*.py

