name: pytest
on: [push]
jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Installs packages
        run: pip3 install -r requirements.txt
      - name: Runs pytest
        run: pytest -v
