name: ruff

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Lint with ruff
      run: |
        # stop the build if there are Python syntax errors or undefined names
        ruff check . --output-format=github --select=E9,F63,F7,F82 --show-fixes
        # exit-zero treats all errors as warnings
        ruff check . --output-format=github --exit-zero

    - name: Format check with ruff
      run: |
        ruff format --check .
